alphagov/verify-cluster-config

README.md

need to update config path to new cluster.yaml location

update config path

---

values.yaml

In preparation for the istio traffic managenent changes coming in https://github.com/alphagov/gsp/pull/268 and https://github.com/alphagov/verify-proxy-node/pull/253

Add CloudHSM IP

---

values.yaml

It begins.
There will need to be a corresponding commit in doc-checking to create
the pipelines for this.

Create verify-doc-checking namespace

---

values.yaml

As title suggests, just adding a build-process for DCS.

Add doc-checking build pipeline

---

values.yaml

as requested by @Wynndow
**!!! Merge alphagov/verify-metadata#334 first !!!**

add verify-connector-node-metadata namespace

---

values.yaml

This is a hack to allow us to do concurrent work in DCS.
Co-authored-by: Benjamin Gill <benjamin.gill@digital.cabinet-office.gov.uk>

BAU: Change staging pipeline to look at build

---

values.yaml

Fixed hacky directory path for doc-checking staging environment

Fix staging path

---

values.yaml

add talksToHsm label

---

values.yaml

To replace https://github.com/alphagov/gsp/pull/468

Add permissions to access VMC resources

---

config/verify-main/ingress-certificate.yaml
values.yaml

Enrol verify-main & canary into per-namespace ingress gateway.

---

ci/psn.yaml

This was renamed in https://github.com/alphagov/gsp/pull/303

Fix name of approvers keys

---

hack/set-pipeline-vars.sh

The psn-vpc-endpoint pipeline uses a hardcoded version of the resource
from this file.

bump github resource version

---

cluster.yaml

Follow up to https://github.com/alphagov/verify-cluster-config/pull/73 - we think we can go further.

Set minimum workers to 1 per AZ

---

cluster.yaml

https://github.com/alphagov/gsp/pull/635

Remove old worker-count key

---

values.yaml

Should be replaced by https://github.com/alphagov/gsp/pull/566

Remove cluster-wide RDS egress rule

---

cluster.yaml

Testing to see if this improves the intermittent build failures seen by
DCS build pipelines.

Scale up ci workers.

---

hack/set-pipeline-vars.sh

It didn't set the `account-role-arn` variable.
It tried to set the wrong pipeline name.
Already applied :cowboy:

fix set-pipeline script

---

terraform/main.tf
terraform/modules/psn/main.tf

Format for new syntax, use .outputs for https://www.terraform.io/upgrade-guides/0-12.html#remote-state-references

Update PSN Terraform module for 0.12 support

---

ci/psn.yaml
terraform/main.tf
terraform/modules/psn/data/psn-network-policy.yaml
terraform/modules/psn/main.tf

Adds a step in the pipeline for applying kubernetes resources and the
necessary plumbing for exposing the resources needed.
Disclaimer: I have no idea if this is going to work!

Create and apply a global network policy for securing PSN access.

---

ci/psn.yaml

This will hopefully fix the missing metadata now that the terraform is
correct.

Factor kubectl apply step into its own job in the pipeline.

---

values.yaml

Awaiting IA approval following satisfying pen-test concerns.

Temporarily disable PSN connectivity in DCS prod.

---

values.yaml

Add a new egress list and place the legacy and new multi-country egress urls in this list.
We believe this list will be interpolated here: https://github.com/alphagov/gsp/blob/52904fc6eb4fc3fec06aa4db9466e9f3ad45c98e/charts/gsp-cluster/templates/02-gsp-system/egress-safelist.yaml#L1

EID-1823 Add a new build egressSafelist to verify cluster config

---

values.yaml

This will be a replacement for dcs-test in UKC/CR.

yyiztr09: Create DCS integration environment

---

cluster-resources/verify_v1beta1_certificaterequest.yaml
cluster-resources/verify_v1beta1_metadata.yaml

Requires:
Should be merged / released with:

Add Metadata Controller CRDs to verify clusters.

---

cluster.yaml

Currently operating at max so add a couple more for headroom.
Co-authored-by: Daniel Blair <daniel.blair@digital.cabinet-office.gov.uk>

9n9gzUkZ - Scale GSP cluster nodes.

---

values.yaml

So we can connect Estonia to MC PN in integration
Also order countries alphabetically

EID-1951: Add Estonia to egress safe list

---

values.yaml

Hosts taken from Proxy Node integration config PR https://github.com/alphagov/verify-eidas-config/pull/23

EID-1973 EU integration connector nodes to egress safelist

---

ci/customdomains.yaml
ci/psn.yaml

See also https://github.com/alphagov/tech-ops-private/pull/389

Update concourse-pipeline-resource to work on newer versions of Concourse

---

values.yaml

Allow egress to prod Spain Connector Node, see https://govuk.zendesk.com/agent/tickets/4138055

🇪🇸 EID-2013 Egress from Proxy Node to prod Spain Connector

---

values.yaml

Remove legacy Proxy Node namespaces

EID-2061 remove legacy Proxy Node namespaces

---

values.yaml

Previous PR wasn't signed, advice was to raise a whitespace PR.
Update comments to reflect current state of Proxy Node.

EID-2061 noop to get a signed commit

---

values.yaml

Allow proxy node to read Belgium's connector node metadata

🇧🇪 Allow egress to  Belgium connector node host
