cluster.yaml

I got a bit carried away and renamed too many things

fix: typo in repo names

---

cluster.yaml

we are getting ready for production, we need more workers as we are (1)
scaling up replicas of proxy-node instances, (2) are seeing scheduling
issues due to anti-affinity rules
we have seen poor performance of concourse workers due to the CPU heavy
builds of the java apps.

scales up number of workers and scale up ci node size

---

values.yaml

Needs to be merged with https://github.com/alphagov/verify-proxy-node/pull/264

Add the NL FQDN to the egress safelist.

---

values.yaml

if you don't have a `verify-` prefix, you don't get a concourse team :(

fix DCS namespaces

---

values.yaml

This safelist entry for the gateway is only in place for the stub
connector, and for consistency this should all live with the proxy node
chart.

Remove duplicate entry for stub connector.

---

values.yaml

The pipeline operator is broken, roughly since #15 was merged.  I have
a hypothesis that this is because we removed the yaml for some
namespaces, and this broke something.  Therefore, I'm hoping to
appease the kubernetes gods and fix the pipeline operator by restoring
this legacy yaml.

restore dead namespaces

---

values.yaml

As a result of alphagov/verify-proxy-node#242
The new instance is live at http://test-integration-connector.london.verify.govsvc.uk

BAU: Add new test integration proxy node instance

---

values.yaml

- Not yet being used for production, testing only.
Co-authored-by: Benjamin Gill <benjamin.gill@digital.cabinet-office.gov.uk>

OGD-279: Remove 1 Eye on doc-checking build.

---

ci/psn.yaml
hack/set-pipeline-vars.sh
terraform/main.tf
terraform/modules/psn/main.tf

The Verify cluster needs to have a VPC endpoint available for the teams
to use PSN. This isn't standard core GSP requirement, therefore the
snowflake is to be living with the verify cluster config.
We will need to apply the module. Instead of just going into this module
directory, we will be calling the module from different terraform file,
which should allow us to nicely separate the potentially sensitive data
from the "logic".
We need to add some extra functionality into the GSP cluster that is
very DCS specific. It needs to be separated out from the GSP logic as it
will not be applied across the board.
We're adding the hack script as:
- The Concourse pipeline doesn't have these variables set by Concourse
from the start, so we need to specify them. Like in `alphagov/gsp`, add
a `hack/` …

Create PSN Endpoint for DCS connection

---

cluster.yaml

We'll enable this at a later date.
The other half of https://github.com/alphagov/gsp/pull/342.

Add `enable-nlb` variable

---

cluster.yaml

Add an NLB so it's possible for tenants to do their own mTLS.

Enable NLB in Verify's cluster

---

values.yaml

Having problems due to `# legacy; needs to be deleted carefully`, so update legacy to match the new desired reality.

BAU: remove restrictions on DCS staging

---

values.yaml

I'm admin today so I can deploy this and delete any underlying
resources we need to delete

remove legacy namespaces

---

terraform/main.tf

- The DCS team need this for testing their environments now the mTLS
work is done.
- This is snowflaked in the same way as the PSN stuff.
Co-authored-by: Daniel Blair <daniel.blair@digital.cabinet-office.gov.uk>
This depends on https://github.com/alphagov/gsp/pull/361 being released, which it isn't yet due to problems with the sandbox pipeline.

Add a CNAME record for dcs-dev.verify pointing at the NLB

---

cluster.yaml

we're hitting resource limits - CPU, memory and pod limits.  This has
meant that istio-pilot is unable to schedule pods.

scale up workers

---

values.yaml

- The pipeline is in a better place now that we should start building from master
so we don't get out of sync.

BAU - Build doc-checking-build from master

---

values.yaml

DCS applications want to talk to OCSP on the Internet. The Online Certificate Status Protocol (OCSP) is an Internet protocol used for obtaining the revocation status of an X.509 digital certificate.
Author: @adityapahuja

Add OCSP to http egress safelist

---

values.yaml

awscli uses this because boto3 does.

Safelist SQS legacy endpoint too

---

values.yaml

we now use the istio ServiceEntry format to describe what services
external to the cluster we allow egress to so that we have full control
over the configuration of ports etc enabling whitelisting non-http
services.
The available options for the `service` block can be found in the Istio
documentation: https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/#ServiceEntry
in addition to reformatting the existing entries, we also add a new
entry for connecting to postgres (rds) services within the eu-west-2
region.
:warning: should merge https://github.com/alphagov/gsp/pull/426

update egress (ServiceEntry) configuration

---

values.yaml

- The Postgres default port of 5432 is not correct. Aurora exposes 3306
for Postgres, which is confusingly also the MySQL port.

Specify the correct port number for RDS Aurora Postgres

---

values.yaml

- We were seeing issues connecting to AWS RDS from Istio-managed
namespaces such that the connection would never get to Amazon, it
would be blocked by Istio, like:
```
psql: server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
```
- This change sets `protocol` to `TCP` instead of `TLS` so that we allow
all traffic on port 3306 to the entire VPC subnet. Maybe we should
clean this up in a later commit? But for now, it unblocks DCS.
Co-authored-by: Issy Long <isabell.long@digital.cabinet-office.gov.uk>
Co-authored-by: Daniel Blair <daniel.blair@digital.cabinet-office.gov.uk>

Fix RDS access from Istio-managed namespaces

---

config/verify-main/ingress-certificate.yaml
values.yaml

Enrol verify-main & canary into per-namespace ingress gateway.

---

README.md

Because "revert" PRs are created by Github, and not any of us.

A noop to allow the build to go through.

---

values.yaml

dcs staging environment is redundent, remove it.
:warning: will require manual cleanup in cluster

remove doc-checking-staging ns

---

terraform/main.tf
terraform/modules/psn/main.tf

Currently, the PSN VPC endpoint is in the "worker" security group,
which is good to get us going but is possibly too permissive.  We only
need access to a single port on the VPC endpoint.
This commit gives the VPC endpoint its own security group and grants
access from the worker security group to the VPC endpoint security
group on port 3128.
This is completely untested; I don't know if the syntax is even valid.  I mainly want to have a conversation about this.

Give the PSN VPC endpoint its own security group

---

terraform/modules/psn/main.tf

Fix missing VPC ID on PSN endpoint security group

---

cluster.yaml

This bumps the worker node size to m5d.xlarge.  This is for IP address
efficiency reasons.
In detail:
- `m5d.large` instances have a maximum of 30 IP addresses.  One is
used by the kubelet, leaving 29 for use by pods.
- `m5d.xlarge` instances are twice the price and have twice the IP
addresses - they have 60 IPs, 59 for use by pods.
- we currently run 8 DaemonSets, which consume 8 of the available IPs
on each node.  This means that actually `m5d.large` nodes have
space for 21 non-daemon pods, while `m5d.xlarge` nodes have space
for 51
- therefore, an `m5d.xlarge` instance is 2x the price but can run
2.4x the pods
This commit bumps the instance size up.  A follow-up PR will reduce
the number of nodes to 6.
Do not merge before alphagov/gsp#580

bump cluster to m5d.xlarge

---

cluster.yaml

We have enough nodes in the per-AZ auto-scaling groups now.
These old ones have been cordoned and drained.

Set old worker count to 0

---

cluster.yaml

When the image type was changed from m5d.large to m5d.xlarge we did not reduce
the number of nodes. We can probably reduce the minimum and see what the
cluster autoscaler comes up with for desired number.

Reduce minimum worker count per AZ by 1

---

ci/psn.yaml

As the PSN endpoint terraform pulls in e.g. worker_security_group_id and that
can change.

Trigger PSN endpoint deployment on GSP cluster state change

---

cluster.yaml

Was replaced with config-approval-count
See https://github.com/alphagov/gsp/pull/303

Remove old github-approval-count key

---

cluster.yaml

The 'd' types aren't useful in EKS land as the local disk gets replaced by
the EBS volume anyway.
Before merge:

Change instance type.

---

values.yaml

```
gds verify k -n verify-doc-checking-prod delete horizontalpodautoscaler.autoscaling/verify-doc-checking-prod-ingressgateway \
deployment.apps/verify-doc-checking-prod-ingressgateway \
service/verify-doc-checking-prod-ingressgateway
```

Temporarily disable ingress for DCS prod

---

terraform/modules/psn/main.tf

The attribute referenced is a set, not a list, and so cannot be accessed by
numeric index. Switching to the for_each mechanic instead.

Fix set vs list interpolation for psn ENIs.

---

ci/psn.yaml

Some of the outputs are missing and/or not populated. Hopefully explicitly
doing a get on the resource populates the missing data.

Explicitly get the psn-state resource in the pipeline.

---

ci/psn.yaml

Brings it inline with the GSP deployer pipelines.

Use `latest` version of terraform resource in psn pipeline.

---

terraform/modules/psn/main.tf

Successfully ran a plan this way in a hijacked container. Worth a try.

Favour an explicit loop over the splat operator.

---

hack/set-pipeline-vars.sh

The pipelines in concourse now require certain values relating to approvers
to be correctly set before they will self-update so the hack script needs
to match.

Add missing setup of the set-pipeline hack script.

---

terraform/modules/psn/data/psn-network-policy.yaml

The "Allow" action will cause calico to stop processing other rules and
allow the packet. This is not intended as other policies contain deny
rules that need to be processed after this (they have a higher "order"
value).

Fix network policy to allow other policies to act.

---

values.yaml

We are building multi-country Proxy Node on master, and want to deploy the legacy single-country version from a release branch.
Feature switching was discussed in the team and discounted for this piece of work.

EID-1822 Build pipelines from legacy Proxy Node branch.

---

values.yaml

IA have now given approval.
We will still need to set up ServiceEntry resources and talksToPsn pod labels before anything can talk, but that happens in doc-checking.git.

Enable DCS prod namespace connection to the PSN

---

ci/psn.yaml

The latest version of the github resource doesn't need this (since
alphagov/gsp#378).  Instead the process is to add your GPG key to
GitHub and get GitHub to verify the signature; we only need to
validate the signature on the GitHub merge commit against the GitHub
web flow key.
Note that if we can get rid of commit_verification_keys from all our
pipelines, we can also merge alphagov/gds-trusted-developers#111 so
that we no longer have to faff with GPG keys in that repository when
people join teams that commit to GSP projects.

remove commit_verification_keys

---

ci/psn.yaml

I missed this reference when doing #100, so the pipeline is broken
because it can't find keys.vars.yaml (which no longer exists).

fix psn pipeline

---

values.yaml

Create new namespace for the new Proxy Node so we can start building master builds again.
Sorry for the TODOs - they will be removed once we get the new deployment to work
Do not merge before appropriate changes have been to the master branch of the Proxy Node in alphagov/verify-proxy-node#404

EID-1823: Separate Proxy Node legacy and master builds

---

values.yaml

Update hostname of test stub-connector in verify cluster.
An update is safe to do as this new test instance is still being configured.

EID-1823 Update hostname of new multi-country test stub-connector

---

values.yaml

This was at 0 but should be at 2 for the time being.

BAU: Increase required approvals for DCS build

---

cluster.yaml

We weren't taking advantage of the difference.
Don't merge this until https://github.com/alphagov/tech-ops-cluster-config/pull/273
has been done and we're happy with the process.

Swap from m5d.xlarge worker nodes to m5.xlarge

---

values.yaml

This is in accordance to an ADR that has been approved by Tom Lee (Verify) and Paul Ellis (IA)
https://github.com/alphagov/doc-checking/pull/773

BAU: Reduce DCS required approvals from 2 to 1

---

values.yaml

This namespace is not currently being used, and there seems to be no likelihood of us needing it in the near future. If we do, re-creating should be simple.

BAU: remove unused 'verify-doc-checking-test'

---

values.yaml

The previous iteration (verify-doc-checking-integration) had too many characters. We are going to use a shortened version to get it deploying successfully.
Once this has been deployed, I'll create a follow-up PR to delete the old environment (and ask an RE person to do the deletion next time they assume admin powers).
This should fix the issue identified by @samcrang: https://gds.slack.com/archives/CHP6D0Q6B/p1578923334028100

BAU: create new DCS integration environment

---

values.yaml

It's name was too long, so we had to [replace it](https://github.com/alphagov/verify-cluster-config/pull/112) with 'verify-dcs-integration' instead. This has been done, so the old one with the longer name can now be removed.
An RE person with admin permissions will be needed to delete everything currently in that namespace after this has been merged.

BAU: remove old DCS integration environment

---

cluster-resources/verify_vmc_clusterrole.yaml
cluster-resources/verify_vmc_clusterrolebinding.yaml

Since https://github.com/alphagov/gsp/pull/855, VMC can't deploy these itself.

Copy in VMC ClusterRole things from verify-metadata-controller

---

values.yaml

Create a new k8s namespace for both the integration and production release in a new namespace called verify-eidas-proxy-node-deploy
PR for the deploy directory in the verify-proxy-node: https://github.com/alphagov/verify-proxy-node/pull/479

EID-1893: create new proxy node namespace for both production and integration

---

cluster.yaml

This doesn't do anything any more since the spot instances work

remove worker-instance-type variable

---

values.yaml

These were all default values and the field is being removed in
https://github.com/alphagov/gsp/pull/977 anyway.

Remove no-op permittedRolesRegex config

---

values.yaml

Add `stub-connector.eidas.integration.london.verify.govsvc.uk` to Verify cluster egress safe list

EID-1894 Allow egress to stub connector integration

---

values.yaml

Add support for verify cluster egress to the stub connector, and also the CNAME on gov.uk to the cluster domain.
Remove the old GSP domains at `stub-connector.eidas.*.london.verify.govsvc.uk` as these have been removed from `gsp-external-dns`.
We'll remove the new GSP cluster domain name that includes the release namespace when test and integration are working.

EID-1964 egress to connector on GSP DNS & gov.uk

---

ci/customdomains.yaml
customdomain-terraform/main.tf
customdomain-terraform/modules/customdomain/main.tf

Add custom domain terraform for eIDAS
So proxy node can get gov.uk domains with automatically-rotated certificates
(where possible).
Existing middleware records copied from GOV.UK as we need to ensure they won't conflict.
New records commented out pending delegation from GOV.UK DNS.

Add custom domain terraform for eIDAS

---

customdomain-terraform/modules/customdomain/main.tf

In experimenting with my CloudFront-distributed-sandbox-canary it seems turning
this off allows CloudFront to connect to our GSP origins. I suspect this is
because with it on, CloudFront will attempt to use the specified Host header,
and then get upset when GSP serves a certificate that does not match that Host.

custom domains: Try removing forwarding of headers

---

customdomain-terraform/modules/customdomain/main.tf

List of headers requested by Phil Miller.
I removed Host and Connection from his list as those probably need to be
controlled by CloudFront for things to work properly.

custom domains: Specify certain types of headers to pass through

---

customdomain-terraform/modules/customdomain/main.tf

And hit the default quota on whitelisted headers to pass through.

customdomain: Remove Upgrade-Insecure-Requests header, we already enforce HTTPS

---

values.yaml

Update the eidas.signin.service.gov.uk domain names to place `test` and `integration` in the correct positions.

EID-1964 rename gov.uk domains for Proxy Node stub-connector

---

values.yaml

So we can connect to the EU Node Validator

EID-1977: Add European Commission to egress safelist

---

ci/customdomains.yaml
ci/psn.yaml

This was introduced in Concourse 5.8 and is fine for changing pipelines within
the same team.

Use set_pipeline instead of concourse-pipeline-resource

---

customdomain-terraform/main.tf

As GSP will (soon) be serving a manually-maintained QWAC certificate that matches
this domain.

CNAME Proxy Node prod directly to GSP without going through a CloudFront reverse proxy

---

customdomain-terraform/main.tf

Reverts alphagov/verify-cluster-config#140
Terraform is being a pain in a couple of ways, first let's deal with the lists and sets stuff Daniel was looking at last week.

Revert "CNAME Proxy Node prod directly to GSP without going through a CloudFront reverse proxy"

---

customdomain-terraform/modules/customdomain/main.tf

See also https://github.com/alphagov/verify-terraform/pull/1271
Been getting errors like:
Error: Invalid index
on modules/customdomain/main.tf line 36, in resource "aws_route53_record" "cert_validation":
36:   name    = aws_acm_certificate.cert.domain_validation_options.0.resource_record_name
This value does not have any indices.

Fix list-vs-set usage

---

customdomain-terraform/main.tf

Reverts alphagov/verify-cluster-config#141
Now that we've done https://github.com/alphagov/verify-cluster-config/pull/142 and terraform is happy again.
This will take a bit of faffing to roll out due to https://github.com/hashicorp/terraform/issues/22907

Re-try "CNAME Proxy Node prod directly to GSP without going through a CloudFront reverse proxy"

---

values.yaml

Allow egress to Estonia Connector Node, [defined here](https://github.com/alphagov/verify-eidas-config/blob/daa4270b6d35e939abdcc85ca08ba7273aa89805/proxy-node/production/countries.yml#L6-L8).

Add Estonia Connector Node to Verify cluster egress safelist

---

customdomain-terraform/main.tf

For while we're between valid QWAC certs.

Make ACM validation record for temporary German Middleware cert

---

values.yaml

We need to be able to read Greece Connector node metadata from host `eidas.gov.gr`.

Allow GSP egress to Greece Prod Connector

---

customdomain-terraform/main.tf

Reverts alphagov/verify-cluster-config#153
This failed to roll out because you can't just delete modules containing providers like that. Will need to have another go.
Deliberately reverting and re-doing instead of fixing forward in this case.

Revert "Clear away all the eIDAS CloudFront distributions etc."
